name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Init Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Rust format check
        run: cargo fmt --check

      - name: Rust clippy
        run: cargo clippy -- -D warnings

      - name: Rust clippy (no_std)
        run: cargo clippy --no-default-features --features no_std -- -D warnings

      - name: Run tests
        run: cargo test

      - name: Run tests (no_std)
        run: cargo test --no-default-features --features no_std -- -D warnings
